from __future__ import annotations

DEFAULT_LANGUAGE_ALLOWLIST = {"simple", "en", "english"}
REPORT_VERSION = "1.0.0"

MODE_WEIGHTS = {
    "transcript": {
        "disfluency_restarts": 1.0,
        "hedging_vagueness": 1.0,
        "lexical_precision": 1.0,
        "coherence_topic_drift": 1.0,
        "argument_structure": 1.0,
        "commitment_agency": 1.0,
        "contradiction_reversal": 1.0,
        "stress_self_protection": 1.0,
    },
    "note": {
        "disfluency_restarts": 0.22,
        "hedging_vagueness": 0.95,
        "lexical_precision": 1.0,
        "coherence_topic_drift": 0.92,
        "argument_structure": 1.0,
        "commitment_agency": 1.0,
        "contradiction_reversal": 0.95,
        "stress_self_protection": 0.88,
    },
}

STOP_WORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "because",
    "been",
    "being",
    "but",
    "by",
    "for",
    "from",
    "had",
    "has",
    "have",
    "he",
    "her",
    "his",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "just",
    "me",
    "my",
    "not",
    "of",
    "on",
    "or",
    "our",
    "she",
    "so",
    "that",
    "the",
    "their",
    "them",
    "there",
    "they",
    "this",
    "to",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "who",
    "will",
    "with",
    "you",
    "your",
}

FILLERS = [
    "um",
    "uh",
    "like",
    "you know",
    "basically",
    "actually",
    "literally",
    "sort of",
    "kind of",
    "i mean",
    "right",
    "okay",
    "well",
]

HEDGES = [
    "maybe",
    "probably",
    "perhaps",
    "i think",
    "i guess",
    "i feel",
    "i don't know",
    "it seems",
    "seems like",
    "in some way",
    "somehow",
    "potentially",
    "possibly",
    "relatively",
    "kind of",
    "sort of",
    "might",
    "could",
]

VAGUE_WORDS = [
    "thing",
    "things",
    "stuff",
    "something",
    "anything",
    "everything",
    "nothing",
    "really",
    "very",
    "quite",
    "pretty",
    "somehow",
    "somewhat",
]

GENERIC_NOUNS = [
    "thing",
    "things",
    "stuff",
    "situation",
    "situations",
    "problem",
    "problems",
    "issue",
    "issues",
    "area",
    "areas",
]

MODALS = ["could", "should", "would", "might", "maybe", "perhaps", "hopefully"]
REVERSAL_MARKERS = [
    "but",
    "however",
    "though",
    "although",
    "at the same time",
    "on the other hand",
    "except",
    "actually",
]

INTENSIFIERS = [
    "crazy",
    "insane",
    "wild",
    "dangerous",
    "terrifying",
    "scary",
    "fucking",
    "hate",
    "awful",
    "brutal",
    "massive",
    "huge",
]

SELF_ATTACK = [
    "inferior",
    "weak",
    "stupid",
    "pathetic",
    "embarrassing",
    "ashamed",
    "failure",
    "flawed",
    "broken",
    "wrong",
    "not enough",
    "robot",
]

FEAR_WORDS = [
    "afraid",
    "fear",
    "scared",
    "anxious",
    "nervous",
    "worry",
    "worried",
    "dread",
]

APOLOGIES = ["sorry", "my fault", "i was wrong", "i messed up", "i fucked up"]

AGENCY_SOFTENERS = [
    "i need to",
    "i should",
    "i want to",
    "i hope",
    "i wish",
    "if only",
]

AGENCY_COMMITMENTS = [
    "i will",
    "i'm going to",
    "i am going to",
    "i decided",
    "i did",
    "i shipped",
    "i built",
    "i recorded",
    "i reached out",
]

AUDIENCE_WORDS = [
    "customer",
    "customers",
    "investor",
    "investors",
    "cofounder",
    "co-founder",
    "friend",
    "friends",
    "team",
    "audience",
    "listener",
    "listeners",
    "mentor",
    "mentors",
    "user",
    "users",
    "people",
]

STRUCTURE_MARKERS = [
    "first",
    "second",
    "third",
    "the point is",
    "for example",
    "for instance",
    "because",
    "which means",
    "in other words",
    "the problem is",
    "the solution is",
    "so that",
]

ANCHOR_MARKERS = [
    "today",
    "tomorrow",
    "yesterday",
    "morning",
    "night",
    "week",
    "month",
    "year",
    "minute",
    "hour",
    "for example",
    "when",
    "after",
    "before",
    "during",
]

ACTION_WORDS = [
    "plan",
    "planning",
    "build",
    "building",
    "write",
    "writing",
    "ship",
    "shipping",
    "apply",
    "practice",
    "improve",
    "improving",
    "learn",
    "fix",
    "execute",
    "record",
    "post",
    "reach out",
    "focus",
    "train",
    "do",
    "doing",
]

CONTEXT_MAP = {
    "startup": {"startup", "investor", "cofounder", "product", "founder", "pitch", "customer"},
    "communication": {"communication", "speaking", "voice", "articulate", "conversation", "explain"},
    "productivity": {"productivity", "schedule", "calendar", "plan", "planning", "focus", "time"},
    "systems": {"system", "systems", "setup", "automation", "automate", "workflow", "markdown", "folder", "cloud", "skill", "skills"},
    "identity": {"identity", "purpose", "self", "confidence", "worth", "potential"},
    "relationships": {"wife", "partner", "friends", "friend", "family", "love", "relationship", "women"},
    "career": {"job", "career", "manager", "work", "team", "interview", "hiring"},
    "spirituality": {"religion", "spirituality", "god", "mindfulness", "intentionality"},
    "health": {"gym", "sleep", "health", "legs", "body", "diet"},
    "content": {"content", "podcast", "video", "social media", "tweet", "post"},
    "learning": {"learn", "learning", "book", "coach", "mentors", "advice"},
}

DIMENSION_LIBRARY = {
    "disfluency_restarts": {
        "label": "Disfluency and restarts",
        "explanation": "The transcript shows frequent mid-thought repairs, fillers, and restart patterns that expose the thinking process before the point lands.",
        "why_it_matters": "Listeners spend effort decoding the sentence shape instead of receiving the idea cleanly.",
        "hypothesis": "This often shows up when you are thinking and speaking at the same time instead of landing the claim first.",
    },
    "hedging_vagueness": {
        "label": "Hedging and vagueness",
        "explanation": "Claims are softened with hedges, vague nouns, and modal language before they fully commit.",
        "why_it_matters": "Softened language reduces authority and makes it harder for the listener to know what you actually believe.",
        "hypothesis": "This can be a self-protective habit that lowers the risk of being wrong in real time.",
    },
    "lexical_precision": {
        "label": "Lexical precision drag",
        "explanation": "Generic wording, repeated abstractions, and low-specificity nouns make the idea broader than it needs to be.",
        "why_it_matters": "When key nouns stay abstract, the listener cannot picture the mechanism, stakes, or request.",
        "hypothesis": "You may understand the internal picture but leave it implicit instead of naming it concretely.",
    },
    "coherence_topic_drift": {
        "label": "Coherence and topic drift",
        "explanation": "The note changes direction abruptly or reopens prior loops before the current thread is resolved.",
        "why_it_matters": "Topic drift weakens retention and makes high-stakes answers feel rambling instead of controlled.",
        "hypothesis": "The internal associations are fast, but the external framing is not holding the thread steady.",
    },
    "argument_structure": {
        "label": "Argument structure weakness",
        "explanation": "Claims often arrive without enough evidence, anchors, examples, or explicit asks around them.",
        "why_it_matters": "Persuasion depends on a visible path from claim to support to outcome, especially in founder-style communication.",
        "hypothesis": "You often know the argument implicitly but do not expose the supporting structure for the listener.",
    },
    "commitment_agency": {
        "label": "Commitment and agency leakage",
        "explanation": "The wording leans toward aspiration, obligation, and external blockers more than decisive ownership.",
        "why_it_matters": "Repeated soft commitment weakens trust that the point will turn into action.",
        "hypothesis": "The language may still be carrying unresolved tension between desire, fear, and execution.",
    },
    "contradiction_reversal": {
        "label": "Contradiction and reversal load",
        "explanation": "The transcript repeatedly flips direction with reversals, caveats, or competing claims in the same stretch.",
        "why_it_matters": "Frequent reversals blur the listener's model of your actual stance.",
        "hypothesis": "You may be trying to keep every nuance alive at once instead of choosing the main frame first.",
    },
    "stress_self_protection": {
        "label": "Stress and self-protection markers",
        "explanation": "Fear language, self-attack, absolutes, and emotionally charged framing show up strongly in the transcript.",
        "why_it_matters": "When pressure language rises, it often distorts clarity, tone, and judgment in the same moment.",
        "hypothesis": "This can reflect real stress, but the interpretation should stay tentative because the signal is transcript-only.",
    },
}

VOCABULARY_TARGETS = [
    {
        "id": "thing_family",
        "label": "thing / things / something / stuff",
        "kind": "word",
        "category": "generic-placeholder",
        "terms": ["thing", "things", "something", "stuff"],
        "why_it_limits_you": "Placeholder nouns hide the actual object, mechanism, or constraint, so the listener cannot picture what you mean.",
        "replacement_options": [
            {"word": "constraint", "useWhen": "You mean a limit, blocker, or condition shaping the outcome.", "caution": "Do not use it for a physical object or feature.", "keywords": ["block", "limit", "hard", "risk", "issue", "problem"], "rewrite_with": "constraint"},
            {"word": "pattern", "useWhen": "You are describing a repeated behavior, habit, or recurring shape.", "caution": "Use it only when repetition is actually present.", "keywords": ["always", "keep", "habit", "again", "repeat", "usually"], "rewrite_with": "pattern"},
            {"word": "decision", "useWhen": "You are really referring to a choice, tradeoff, or judgment call.", "caution": "Avoid it if no one is deciding anything.", "keywords": ["choose", "choice", "plan", "should", "decide", "option"], "rewrite_with": "decision"},
            {"word": "feature", "useWhen": "The vague word is standing in for a product capability or workflow step.", "caution": "Only use it for actual product behavior.", "keywords": ["product", "app", "tool", "user", "build", "startup"], "rewrite_with": "feature"},
            {"word": "request", "useWhen": "You are pointing to an ask, need, or instruction.", "caution": "Do not use it when you mean a problem or object.", "keywords": ["ask", "need", "want", "should", "team", "someone"], "rewrite_with": "request"},
        ],
        "practice_focus": [
            "Ban this family for one recording and force yourself to name the object or mechanism.",
            "If you say one of these words, pause and replace it with a concrete noun before continuing.",
            "After each note, rewrite one vague sentence in fewer words with a named object and one example.",
        ],
    },
    {
        "id": "people_family",
        "label": "people / person / someone",
        "kind": "word",
        "category": "generic-audience",
        "terms": ["people", "person", "someone"],
        "why_it_limits_you": "Generic audience words blur who the message is actually about, which weakens persuasion and empathy.",
        "replacement_options": [
            {"word": "customer", "useWhen": "The person is evaluating, buying, or using a product.", "caution": "Only use it in market or product contexts.", "keywords": ["product", "startup", "buyer", "user", "market", "customer"], "rewrite_with": "customer"},
            {"word": "listener", "useWhen": "You are describing the person hearing or interpreting your words.", "caution": "Use it only in speaking or explanation contexts.", "keywords": ["communication", "speak", "conversation", "explain", "voice", "audience"], "rewrite_with": "listener"},
            {"word": "teammate", "useWhen": "The vague person is a collaborator, employee, or cofounder.", "caution": "Avoid it for customers or strangers.", "keywords": ["team", "work", "cofounder", "manager", "job", "career"], "rewrite_with": "teammate"},
            {"word": "founder", "useWhen": "You are describing startup peers, operators, or company builders.", "caution": "Only use it if that identity matters to the point.", "keywords": ["startup", "pitch", "investor", "founder", "company", "build"], "rewrite_with": "founder"},
            {"word": "friend", "useWhen": "The person is part of a personal relationship or social setting.", "caution": "Do not use it for formal or business contexts.", "keywords": ["friend", "friends", "relationship", "family", "partner", "wife"], "rewrite_with": "friend"},
        ],
        "practice_focus": [
            "Name the exact audience in your first sentence whenever you notice yourself saying 'people'.",
            "Keep a running list of the five audience labels you use most often: customer, listener, teammate, founder, friend.",
            "During review, circle every generic person-word and ask which role that human actually plays in the story.",
        ],
    },
    {
        "id": "way_family",
        "label": "way",
        "kind": "word",
        "category": "generic-structure",
        "terms": ["way"],
        "why_it_limits_you": "Way is often a placeholder for method, sequence, mechanism, or signal. The listener has to guess which one you mean.",
        "replacement_options": [
            {"word": "approach", "useWhen": "You mean a deliberate method or strategy.", "caution": "Use it for chosen methods, not automatic processes.", "keywords": ["plan", "strategy", "method", "solve", "practice", "improve"], "rewrite_with": "approach"},
            {"word": "sequence", "useWhen": "You are describing order, steps, or progression.", "caution": "Only use it when order matters.", "keywords": ["first", "second", "then", "next", "before", "after"], "rewrite_with": "sequence"},
            {"word": "mechanism", "useWhen": "You mean the causal process behind an outcome.", "caution": "Do not use it as a fancy synonym for method.", "keywords": ["because", "causes", "result", "system", "works", "process"], "rewrite_with": "mechanism"},
            {"word": "signal", "useWhen": "You are pointing to an indicator or cue.", "caution": "Only use it when the point is diagnostic.", "keywords": ["notice", "sign", "indicator", "shows", "means", "suggests"], "rewrite_with": "signal"},
        ],
        "practice_focus": [
            "Replace 'way' with one of four buckets: approach, sequence, mechanism, or signal.",
            "If you cannot replace it, the sentence probably still hides the real idea.",
            "Use this as a diagnostic for whether your explanation is procedural, causal, or observational.",
        ],
    },
    {
        "id": "really_very",
        "label": "really / very",
        "kind": "word",
        "category": "intensifier",
        "terms": ["really", "very"],
        "why_it_limits_you": "Repeated intensifiers make the sentence feel emotionally weighted without adding much information.",
        "replacement_options": [
            {"word": "remove the intensifier", "useWhen": "The adjective is already strong enough on its own.", "caution": "Do not remove it if intensity is the entire point of the sentence.", "keywords": ["good", "bad", "hard", "important", "clear", "useful"], "rewrite_with": ""},
            {"word": "choose a sharper adjective", "useWhen": "A stronger adjective would carry the meaning more cleanly.", "caution": "Do not reach for a dramatic word that overstates the reality.", "keywords": ["good", "interesting", "bad", "hard", "important", "problem"], "rewrite_with": ""},
            {"word": "use a number or condition", "useWhen": "You can quantify instead of amplifying.", "caution": "Use it only when you have a real count, time, or constraint.", "keywords": ["days", "hours", "times", "cost", "money", "more"], "rewrite_with": ""},
        ],
        "practice_focus": [
            "On replay, delete every 'really' and 'very' first, then add back only the ones that still earn their place.",
            "Trade one intensifier per day for one sharper adjective or one measurable fact.",
            "If you hear yourself reaching for intensity, ask whether you mean urgency, magnitude, or quality.",
        ],
    },
    {
        "id": "good_family",
        "label": "good / interesting / crazy",
        "kind": "word",
        "category": "generic-evaluation",
        "terms": ["good", "interesting", "crazy", "weird", "nice"],
        "why_it_limits_you": "Generic evaluative words announce a reaction without telling the listener what quality produced that reaction.",
        "replacement_options": [
            {"word": "useful", "useWhen": "The value is practical or helps the other person act.", "caution": "Do not use it if the point is emotional or aesthetic.", "keywords": ["help", "practical", "action", "solve", "improve", "productivity"], "rewrite_with": "useful"},
            {"word": "compelling", "useWhen": "The point is persuasive, attractive, or hard to ignore.", "caution": "Use it for arguments, hooks, or products that pull attention.", "keywords": ["pitch", "argument", "story", "audience", "investor", "founder"], "rewrite_with": "compelling"},
            {"word": "revealing", "useWhen": "Something taught you something important or exposed a pattern.", "caution": "Only use it when insight is the point.", "keywords": ["learn", "show", "noticed", "pattern", "signal", "insight"], "rewrite_with": "revealing"},
            {"word": "damaging", "useWhen": "The issue creates real downside or harm.", "caution": "Do not use it for minor inconvenience.", "keywords": ["problem", "risk", "harm", "lose", "failure", "bad"], "rewrite_with": "damaging"},
            {"word": "unexpected", "useWhen": "The point is surprise, not intensity.", "caution": "Avoid it if the surprise is obvious or trivial.", "keywords": ["surprise", "suddenly", "weird", "different", "odd"], "rewrite_with": "unexpected"},
        ],
        "practice_focus": [
            "When you say 'good' or 'interesting', finish the sentence with 'because it is...' and name the quality.",
            "Build a short personal bank of evaluation words: useful, compelling, revealing, damaging, unexpected.",
            "After each recording, upgrade three generic reactions into quality-specific adjectives.",
        ],
    },
    {
        "id": "problem_family",
        "label": "problem / issue / idea",
        "kind": "word",
        "category": "generic-abstraction",
        "terms": ["problem", "issue", "idea"],
        "why_it_limits_you": "These abstract nouns stay one level above the actual failure mode, need, or proposal.",
        "replacement_options": [
            {"word": "bottleneck", "useWhen": "The point is a constraint slowing progress.", "caution": "Use it only when throughput or pace is affected.", "keywords": ["slow", "delay", "stuck", "time", "workflow", "process"], "rewrite_with": "bottleneck"},
            {"word": "objection", "useWhen": "The point is resistance from another person.", "caution": "Do not use it for technical problems.", "keywords": ["investor", "customer", "pushback", "question", "doubt", "pitch"], "rewrite_with": "objection"},
            {"word": "proposal", "useWhen": "You are describing a suggestion, plan, or recommendation.", "caution": "Use it only when the idea is concrete enough to be presented.", "keywords": ["plan", "should", "want", "build", "solution", "suggest"], "rewrite_with": "proposal"},
            {"word": "failure mode", "useWhen": "The point is the way a system or habit breaks down.", "caution": "Avoid it for purely emotional or relational friction.", "keywords": ["break", "fails", "collapse", "mistake", "error", "system"], "rewrite_with": "failure mode"},
        ],
        "practice_focus": [
            "Every time you say 'problem', ask whether it is a bottleneck, objection, failure mode, or proposal gap.",
            "Force one level of specificity below the abstraction before you move on.",
            "This family is a good trigger for adding an example or observed moment immediately after the noun.",
        ],
    },
    {
        "id": "i_think_feel_guess",
        "label": "I think / I feel / I guess",
        "kind": "phrase",
        "category": "stance-softener",
        "terms": ["i think", "i feel", "i guess"],
        "why_it_limits_you": "These openers soften your stance before the claim arrives, which trains the listener to discount what follows.",
        "replacement_options": [
            {"word": "My view is", "useWhen": "You have an actual position and want to own it cleanly.", "caution": "Do not use it for guesses you have not thought through.", "keywords": ["belief", "opinion", "view", "point", "stance"], "rewrite_with": "My view is"},
            {"word": "The core point is", "useWhen": "You want to compress the argument into one direct sentence.", "caution": "Only use it when you can actually state the point sharply.", "keywords": ["point", "claim", "argument", "pitch", "explain"], "rewrite_with": "The core point is"},
            {"word": "drop the opener", "useWhen": "The sentence stands on its own without any preface.", "caution": "Keep some uncertainty language later if the claim is genuinely uncertain.", "keywords": ["direct", "clear", "claim", "should", "need"], "rewrite_with": ""},
        ],
        "practice_focus": [
            "Record one answer a day where the first sentence cannot begin with a stance-softener.",
            "If uncertainty matters, move it to the second sentence and keep the first sentence clean.",
            "Treat these phrases as a signal that you should clarify your actual position before you speak.",
        ],
    },
    {
        "id": "you_know",
        "label": "you know",
        "kind": "phrase",
        "category": "filler-phrase",
        "terms": ["you know"],
        "why_it_limits_you": "This phrase asks the listener to bridge the gap for you instead of letting the sentence carry itself.",
        "replacement_options": [
            {"word": "pause", "useWhen": "You need a beat to think and can hold silence instead.", "caution": "The pause should be deliberate, not a new filler habit.", "keywords": ["pause", "breathe", "think", "slow"], "rewrite_with": ""},
            {"word": "for example", "useWhen": "You were reaching for shared understanding but really needed an example.", "caution": "Only use it if an example immediately follows.", "keywords": ["example", "story", "instance", "show"], "rewrite_with": "for example"},
            {"word": "which means", "useWhen": "You need to connect the idea to its implication.", "caution": "Use it only if the next clause actually explains the consequence.", "keywords": ["means", "result", "therefore", "so"], "rewrite_with": "which means"},
        ],
        "practice_focus": [
            "Replace this phrase with a silent beat first. If the sentence still feels thin, add an example instead.",
            "Mark every 'you know' in a transcript and check whether the real missing piece was an example or implication.",
            "This is a useful drill target because it often appears right before the point could have landed cleanly.",
        ],
    },
    {
        "id": "kind_of_sort_of",
        "label": "kind of / sort of",
        "kind": "phrase",
        "category": "blur-phrase",
        "terms": ["kind of", "sort of"],
        "why_it_limits_you": "These blur phrases lower precision right at the moment the listener needs sharper wording.",
        "replacement_options": [
            {"word": "roughly", "useWhen": "You mean approximate magnitude or a loose estimate.", "caution": "Use it only for quantity or degree.", "keywords": ["approximate", "estimate", "about", "around"], "rewrite_with": "roughly"},
            {"word": "partly", "useWhen": "You mean one contributing factor rather than the whole cause.", "caution": "Do not use it when the issue is uncertainty rather than partial contribution.", "keywords": ["part", "factor", "contribute", "cause", "mixed"], "rewrite_with": "partly"},
            {"word": "drop the blur phrase", "useWhen": "The claim is already clear enough without softening.", "caution": "If the claim is truly approximate, replace it with a precise qualifier instead of pretending certainty.", "keywords": ["clear", "direct", "claim", "point"], "rewrite_with": ""},
        ],
        "practice_focus": [
            "Upgrade each blur phrase into the precise type of qualifier you actually mean: roughly, partly, occasionally, or not at all.",
            "If you cannot name the qualifier, the blur phrase is probably hiding a thought you have not pinned down.",
            "This family pairs well with lexical-precision review because it usually appears beside vague nouns.",
        ],
    },
]

VOCABULARY_CONTEXT_BANKS = {
    "communication": [
        {"word": "framing", "useWhen": "You mean the angle or interpretive lens that shapes how a point is received.", "example": "The framing made the answer sound defensive instead of decisive."},
        {"word": "throughline", "useWhen": "You need a word for the main thread connecting your points.", "example": "The throughline disappears when the answer opens too many loops."},
        {"word": "qualifier", "useWhen": "You want to name a hedge or narrowing phrase precisely.", "example": "That qualifier weakens the opening sentence."},
        {"word": "cadence", "useWhen": "You are describing pace and sentence rhythm in speech.", "example": "A steadier cadence would make the idea land harder."},
        {"word": "precision", "useWhen": "You want one word for verbal exactness and specificity.", "example": "The explanation needs more precision in the middle."},
    ],
    "startup": [
        {"word": "traction", "useWhen": "You mean evidence that a market or product is pulling.", "example": "The pitch needs one traction signal, not a vague promise."},
        {"word": "retention", "useWhen": "You are talking about whether users keep coming back.", "example": "Retention matters more than signups in this argument."},
        {"word": "objection", "useWhen": "A listener pushes back on the logic, risk, or premise.", "example": "That investor objection needs a cleaner answer."},
        {"word": "distribution", "useWhen": "You mean how the product reaches people.", "example": "Distribution is the constraint, not product quality."},
        {"word": "friction", "useWhen": "You need a short word for resistance in a workflow or conversion path.", "example": "Too much friction kills the demo before the value is obvious."},
    ],
    "productivity": [
        {"word": "constraint", "useWhen": "A limit or condition shapes what is possible.", "example": "Energy is the real constraint, not motivation."},
        {"word": "sequence", "useWhen": "Order matters and you need to name the order explicitly.", "example": "The morning sequence matters more than the task list."},
        {"word": "trigger", "useWhen": "You need a word for the cue that starts a behavior.", "example": "The trigger should happen before the phone comes out."},
        {"word": "throughput", "useWhen": "You are describing how much work moves through a system over time.", "example": "The workflow has low throughput because context switching is constant."},
        {"word": "blocker", "useWhen": "A specific obstacle stops progress.", "example": "Clarity is the blocker, not effort."},
    ],
    "systems": [
        {"word": "workflow", "useWhen": "You are talking about a repeatable process or operating pattern.", "example": "The workflow is the real unit of automation here."},
        {"word": "automation", "useWhen": "A tool or rule takes over a repeatable action.", "example": "Automation should target the actual bottleneck, not a random task."},
        {"word": "stack", "useWhen": "You mean the set of tools and layers working together.", "example": "The stack matters less than the workflow it supports."},
        {"word": "integration", "useWhen": "You are describing how tools or files connect.", "example": "The integration only matters if it removes a real bottleneck."},
        {"word": "specification", "useWhen": "You mean the written instruction set or contract behind a system.", "example": "The specification should encode the workflow, not just the tool list."},
    ],
    "identity": [
        {"word": "standard", "useWhen": "You mean the bar you expect yourself to meet.", "example": "The standard is clear; the execution is not."},
        {"word": "avoidance", "useWhen": "You are naming behavior that evades discomfort instead of solving it.", "example": "The rambling is a form of avoidance under pressure."},
        {"word": "baseline", "useWhen": "You need a reference level for comparison.", "example": "Your baseline energy changes the way the transcript reads."},
        {"word": "conviction", "useWhen": "You mean inner certainty or owned belief.", "example": "The sentence needs more conviction and less hedging."},
        {"word": "self-concept", "useWhen": "You are talking about the identity model you carry around yourself.", "example": "The self-concept behind the note sounds unstable."},
    ],
    "relationships": [
        {"word": "boundary", "useWhen": "You mean a clear interpersonal limit.", "example": "The conversation needs a boundary, not more explanation."},
        {"word": "repair", "useWhen": "You are talking about restoring trust after friction.", "example": "The conflict needs repair before it needs analysis."},
        {"word": "reciprocity", "useWhen": "The issue is mutual give-and-take.", "example": "The resentment comes from low reciprocity."},
        {"word": "expectation", "useWhen": "You want to name the standard one side assumed.", "example": "The disappointment came from an unstated expectation."},
        {"word": "resentment", "useWhen": "A relationship problem is driven by accumulated unresolved hurt.", "example": "The note sounds like resentment, not confusion."},
    ],
    "content": [
        {"word": "hook", "useWhen": "You mean the opening idea that grabs attention.", "example": "The hook is too abstract to earn attention."},
        {"word": "premise", "useWhen": "You want one word for the central idea underneath the piece.", "example": "The premise is strong but the delivery drifts."},
        {"word": "narrative", "useWhen": "You are describing the story frame or arc.", "example": "The narrative needs a tighter before-and-after structure."},
        {"word": "retention", "useWhen": "You mean how long the audience keeps watching or paying attention.", "example": "Retention drops when the point arrives too late."},
        {"word": "audience", "useWhen": "You need a clearer word than people for who the content serves.", "example": "The audience is founders, not everyone."},
    ],
}
